Feature/api integration
fefdfea1/officeFinder_Front pull request #114
Opened 2023-09-10 18:39 UTC by kjewt

1. agent api 연결 거의 완료했습니다. ( 리뷰 조회, 매출 조회, 예약자 수락거절, 오피스 추가하기, 내 오피스 보기)

- 미구현된 부분
> 내가 등록한 오피스 수정하기 (더 찾아봐야함)
> AllReviews api 수정 예정 (리뷰가 없는 경우 400에러가 뜨도록 구현한 상태라 빈 배열로 받을 수 있도록 요청함) 

2. ui 살짝 변경했습니다.
- chat 영역
- OfficeOptions grid로 변경

3. Input에 props 추가
- 오피스 수정을 위해 defaultValue를 추가했습니다.

2023-09-11 15:17 UTC, minyyi approved these changes

2023-09-12 04:14 UTC, fefdfea1 approved these changes

2023-09-12 04:17 UTC, fefdfea1 requested changes
![스크린샷 2023-09-12 131635](https://github.com/fefdfea1/officeFinder_Front/assets/46808357/d2d7c5de-35bd-4799-8356-ef8733466229)

지금 여기서 지은님이 담당하신 부분에 오류가 있다면 수정해주세요

2023-09-12 11:57 UTC, kjewt commented
@fefdfea1 @minyyi 제 담당 컴포넌트는 안 보입니다. 읽어보니 주로 button에 아직 text가 있어서 발생하는 오류같습니다. Button에 props가 수정되었는데 여전히 text props가 사용되서 생기는 오류같아요.

2023-09-12 17:28 UTC, minyyi approved these changes

2023-09-13 09:42 UTC, fefdfea1 approved these changes

2023-09-13 09:43 UTC, merged