Feature/noti1
fefdfea1/officeFinder_Front pull request #84
Opened 2023-09-03 12:56 UTC by minyyi

라우터 추가 (/Noti)
프리티어 변경으로 인해 ' -> " 로 수정
리스트, 알림메시지 목업데이터로 변경
페이지네이션 추가
서치컴포넌트 내 주석 삭제
서치 영역 수정 하였습니다.

2023-09-03 13:12 UTC, fefdfea1 requested changes
![스크린샷 2023-09-03 221113](https://github.com/fefdfea1/officeFinder_Front/assets/46808357/3d90a2ff-973c-4126-b314-ff7f4bfe053c)
해당 부분 오류가 발생합니다 만약 index를 꼭 사용해야 한다면 v를 _로 사용하지 않고 넘길 수 있습니다

2023-09-04 04:31 UTC, minyyi commented
알려주신대로 수정 했습니다~!

2023-09-04 07:20 UTC, fefdfea1 approved these changes

2023-09-04 07:25 UTC, kjewt approved these changes

2023-09-05 06:26 UTC, merged