Feature/apitest1
fefdfea1/officeFinder_Front pull request #95
Opened 2023-09-06 14:49 UTC by minyyi

axios파일 추가
회원가입에 로직추가
현재 로그인은 일반회원 api통신으로 연결해둔 상태입니다. 
button 공용컴포넌트 프롭스 수정이 있습니다. reactnode를 children으로 받도록 수정하여 text를 p나 span태그로 수정하셔야 할 것 같습니다...ㅠ

2023-09-06 17:52 UTC, fefdfea1 approved these changes

2023-09-06 17:53 UTC, fefdfea1 requested changes
![스크린샷 2023-09-07 025256](https://github.com/fefdfea1/officeFinder_Front/assets/46808357/b09f0ff5-c088-4fc0-85c2-617fdde16cb3)
다음과 같은 오류가 생기네요

2023-09-07 05:43 UTC, kjewt approved these changes

2023-09-07 05:44 UTC, fefdfea1 approved these changes

2023-09-07 05:44 UTC, closed without merging